name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1

      - name: Install
        run: yarn
      - name: Build
        run: yarn build
        
      - name: Percy Test
        uses: percy/exec-action@master
        with:
          command: "mocha --opts ./mocha.opts tests/*spec.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  release: